inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Rails/TimeZone:
  Enabled: true

Style/DateTime:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space
