#TODO: セキュアな値を環境変数に設定すること
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
#    environment:
#      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    environment:
      PAWTH_DOCKER_LOCAL: "true"
    depends_on:
      - db
    ports:
#      - '80:3000'
      - '3001:3000'
    volumes:
      - ./log:/app/log
      - ./storage:/app/storage
    restart: always

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: pawth
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pawth_prod
    # ports:
    #   - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:
