ARG RUBY_VERSION=3.4.7
FROM docker.io/library/ruby:$RUBY_VERSION-slim AS base

# 必要なOSパッケージをインストール
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    build-essential git curl nodejs npm libpq-dev \
    libyaml-dev pkg-config \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

CMD ["bash", "-c", "rm -f tmp/pids/server.pid && bundle exec foreman start -f Procfile.dev"]
